version: "1.0"
info:
  model: int-scaffold
packages:
- name: SE_BS_Demo_2025Project
  gitServerName: SE_BS_GIT
  gitUrl: https://github.com/BjornSkanberg1
  gitUsername: BjornSkanberg1
  gitBranch: main
